### ISSUE TITLE
The index is a little fat, is it worth the cost?

### ISSUE THREAD

**Issue by pfrazee** [township/township-auth#1]
Right now the indexes are storing the full auth object. That means you can read by email with one disk RT, but you're duplicating the entire object to do that. (If you have multiple providers, you'll duplicate it once for each provider.)

Is the speed benefit worth that? For 2 disk RTs you can do `email => key` then `key => data`.

**Comment by sethvincent** [comment]
Under the hood this uses [level-indexer](https://github.com/mafintosh/level-indexer) and it stores the indexes with keys like this:

```
!township-auth-indexes!provider-key!encoded-provider-identifier!auth-key
```

The value is just the `auth-key`.

I'm pretty sure it's doing what you suggest: one read to get the key, another to get the full data.

**Comment by pfrazee** [comment]
Oh, you're right. I assumed level-index called the map method on write time, not sure why. Thanks!
